name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # change if your default branch is different

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        
      - name: Create serviceAccount.json
        run: |
          mkdir -p src/lib/firebase
          # Or if using base64:
           echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}" | base64 --decode > src/lib/firebase/serviceAccount.json
           cat src/lib/firebase/serviceAccount.json
           
          ls -l src/lib/firebase/serviceAccount.json # Check file size and permissions

      - name: Build SvelteKit app
        run: npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SITE_MASHRIQ_MAGHREB_COMPASS }}
          channelId: live
