name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # change if your default branch is different

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        
      - name: Create serviceAccount.json
        run: |
          mkdir -p src/lib/firebase
          # Or if using base64:
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_SITE_MASHRIQ_MAGHREB_COMPASS  }}" | base64 --decode > src/lib/firebase/serviceAccount.json
      - name: Debug VAPID Public Key Length and Content
        run: |
              echo "VAPID_PUBLIC_KEY received by build step: '${{ secrets.VAPID_PUBLIC_KEY }}'" # Use quotes to see leading/trailing spaces
              echo "Length of VAPID_PUBLIC_KEY: ${{ secrets.VAPID_PUBLIC_KEY }}:" $(echo -n "${{ secrets.VAPID_PUBLIC_KEY }}" | wc -c)
              echo "Checking for problem characters:"
              echo "${{ secrets.VAPID_PUBLIC_KEY }}" | grep '=' && echo "Found equals sign!" || echo "No equals signs found (good)"
              echo "${{ secrets.VAPID_PUBLIC_KEY }}" | grep '+' && echo "Found plus sign!" || echo "No plus signs found (good)"
              echo "${{ secrets.VAPID_PUBLIC_KEY }}" | grep '/' && echo "Found slash sign!" || echo "No slash signs found (good)"
              # Use od -c to see any invisible characters
              echo "Raw byte representation:"
              echo "${{ secrets.VAPID_PUBLIC_KEY }}" | od -c
        env:
              VAPID_PUBLIC_KEY: ${{ secrets.VAPID_PUBLIC_KEY }} # Ensure it's passed for the build step too!

      - name: Build SvelteKit app
        run: |
              echo "VAPID_PUBLIC_KEY received by build step: ${VAPID_PUBLIC_KEY}"
              # You could even try to validate it in the shell, though not strictly necessary
               echo "${VAPID_PUBLIC_KEY}" | grep '=' || echo "No equals signs found (good)"
               echo "${VAPID_PUBLIC_KEY}" | grep '+' || echo "No plus signs found (good)"
               echo "${VAPID_PUBLIC_KEY}" | grep '/' || echo "No slash signs found (good)"
              npm run build
        env:
          # Make sure ADMIN_EMAIL is available during the build
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
          SUBSCRIPTION_DB_PATH: ${{ secrets.SUBSCRIPTION_DB_PATH }}
          VAPID_PUBLIC_KEY: ${{ secrets.VAPID_PUBLIC_KEY }}
          VAPID_PRIVATE_KEY: ${{ secrets.VAPID_PRIVATE_KEY }}
          PUBLIC_CLOUDINARY_UPLOAD_PRESET: ${{ secrets.PUBLIC_CLOUDINARY_UPLOAD_PRESET }}
          PUBLIC_CLOUDINARY_CLOUD_NAME: ${{ secrets.PUBLIC_CLOUDINARY_CLOUD_NAME }}
          VITE_MEASUREMENT_ID: ${{ secrets.VITE_MEASUREMENT_ID }}
          VITE_APP_ID: ${{ secrets.VITE_APP_ID }}
          VITE_MESSAGING_SENDERID: ${{ secrets.VITE_MESSAGING_SENDERID }}
          VITE_STORAGE_BUCKET: ${{ secrets.VITE_STORAGE_BUCKET }}
          VITE_PROJECT_ID: ${{ secrets.VITE_PROJECT_ID }}
          VITE_AUTH_DOMAIN: ${{ secrets.VITE_AUTH_DOMAIN }}
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SITE_MASHRIQ_MAGHREB_COMPASS }}
          channelId: live
